name: 'Smelly Python: Smell My PR'
description: 'TODO'
branding:
  icon: 'message-square'
  color: 'orange'
inputs:
  command: 
    description: The folder containing python files for pylint.
    required: true
    default: smelly-python -f src
  github-token:
    description: Github token
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    # Generate report
    - name: Generate report from smelly-python
      shell: bash
      run: ${{ inputs.command }}
    - name: Move to known location
      shell: bash
      run: cp ${{ github.workspace }}/report/smelly_python/comment.md ${{ github.workspace }}/report/smelly_python/comment-$(date -d "today" +"%Y%m%d%H%M").md 
    - name: Save .md report
      uses: actions/upload-artifact@v3
      with: 
        name: smelly-python-${{ github.action }}.md
        path: ${{ github.workspace }}/report/smelly_python/comment-*.md
    - name: Save output folder with html files
      uses: actions/upload-artifact@v3
      with:
        name: smelly-python-${{ github.action }}.html
        path: ${{ github.workspace }}/report/smelly_python/*.html
    - name: Download report 
      uses: actions/download-artifact@v3
      with:
        name: smelly-python-${{ github.action }}.md
    - name: Set job summary
      shell: bash
      run: cat ${{ github.workspace }}/report/smelly_python/comment.md >> $GITHUB_STEP_SUMMARY
    - name: Get PR number
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: echo "pr_number=`gh pr view ${GITHUB_REF_NAME} --json number -q '.number'`" >> $GITHUB_ENV
    - name: Delete old comments
      if: ${{ env.pr_number != '' }}
      uses: maheshrayas/action-pr-comment-delete@v1
      with:
          github_token: ${{ inputs.github-token }}
          org: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name}}
          user: github-actions[bot] #commented by the userid
          issue: ${{ env.pr_number }}
    - name: Post comment
      if: ${{ env.pr_number != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: gh pr comment ${GITHUB_REF_NAME} -F ${{ github.workspace }}/report/smelly_python/comment.md
