name: 'Smelly Python: Smell My PR'
description: 'TODO'
branding:
  icon: 'message-square'
  color: 'orange'
inputs:
  command: 
    description: The folder containing python files for pylint.
    required: true
    default: smelly-python -f src
  github-token:
    description: Github token
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    # Generate report
    - name: Generate report from smelly-python
      shell: bash
      run: ${{ inputs.command }}
    - name: Move to known location
      shell: bash
      run: cp ${{ github.workspace }}/report/smelly_python/comment.md ${{ github.workspace }}/report/smelly_python/comment-$(date -d "today" +"%Y%m%d%H%M").md 
    - name: Save .md report
      uses: actions/upload-artifact@v3
      with: 
        name: smelly-python-${{ github.action }}.md
        path: ${{ github.workspace }}/report/smelly_python/comment-*.md
    - name: Save output folder with html files
      uses: actions/upload-artifact@v3
      with:
        name: smelly-python-${{ github.action }}.html
        path: ${{ github.workspace }}/report/smelly_python/*.html
    - name: Download report 
      uses: actions/download-artifact@v3
      with:
        name: smelly-python-${{ github.action }}.md
    - name: Post comment
      uses: danielhs1/comment-on-pr@v1.3.2
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with: 
        msg: ${{ github.workspace }}/report/smelly_python/comment.md 
